config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { registrations: "user/registrations"  }
  resources :genres
  mount Tail::Engine, at: "/tail"
  root 'welcome#index'
  resources :movies

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  mount_uploader :poster, PosterUploader

  belongs_to :genre
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movie, dependent: :destroy
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]
before_action :authenticate_admin!, only: [:edit, :update, :desroy, :create, :show]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :attribute
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :desroy, :create]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /movies
  # GET /movies.json
  def index
    @movies = current_user.movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params[:movie]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @movies = Movie.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/genres/_form.html.haml
= form_for(@genre, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @genre.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@genre.errors.count, "error")
        prohibited this genre from being saved:
      %ul
        - @genre.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/genres/edit.html.haml
.page-header
  = link_to genres_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @genre, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing genre
= render 'form'

app/views/genres/index.html.haml
.page-header
  = link_to new_genre_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Genre
  %h1 Listing genres
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
        %th
        %th
    %tbody
      = content_tag_for(:tr, @genres) do |genre|
        %td= genre.name
        %td= link_to 'Show', genre
        %td= link_to 'Edit', edit_genre_path(genre)
        %td= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' }

app/views/genres/new.html.haml
.page-header
  = link_to genres_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New genre
= render 'form'

app/views/genres/show.html.haml
.page-header
  = link_to genres_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_genre_path(@genre), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show genre
%dl.dl-horizontal
  %dt Name:
  %dd= @genre.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Moviecub
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <haml_loud> javascript_include_tag &quot;https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js&quot;, &quot;https://oss.maxcdn.com/respond/1.4.2/respond.min.js&quot; </haml_loud>
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "MovieCub", root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if admin_signed_in?
              %li
                = link_to "Add new user", new_user_registration_path
              %li
                = link_to "Genre", genres_path
            - if user_signed_in?
              %li
                = link_to "My movies", movies_path
              %li
                = link_to "Add movie", new_movie_path
          %ul.nav.navbar-nav.navbar-right
            - if admin_signed_in?
              %li
                = link_to "Logout", destroy_admin_session_path, method: :delete
            - if user_signed_in?
              %li
                = link_to "Sign out", destroy_user_session_path, method: :delete
            - unless(user_signed_in? || admin_signed_in?)
              %li
                = link_to "Sign in", new_user_session_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          = msg
      = yield

app/views/movies/_form.html.haml
= form_for(@movie, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @movie.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@movie.errors.count, "error")
        prohibited this movie from being saved:
      %ul
        - @movie.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .col-md-6.col-md-offset-3
      %label Movie name
      = f.text_field :movie_name
    .col-md-6.col-md-offset-3
      %label Genre
      = f.text_field :genre
    .col-md-6.col-md-offset-3
      %label Released year
      = f.select :year_released, (Time.zone.now.year - 100)..(Time.zone.now.year + 1)
    .col-md-6.col-md-offset-3
      %label description
      = f.text_area :description
    .col-md-6.col-md-offset-3
      %label Film poster
      = f.file_field :poster
      = f.hidden_field :poster_cache
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/movies/edit.html.haml
.page-header
  = link_to movies_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @movie, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing movie
= render 'form'

app/views/movies/index.html.haml
.page-header
  %h1 Listing movies
.row
  - @movies.each do |movie|
    = link_to movie do
      .col-xs-6.col-sm-6.col-md-4.col-lg-4
        .foto
          = image_tag movie.poster.url(:thumb) if movie.poster.url
        .caption
          %h3= movie.movie_name
          %h3= link_to 'Edit', edit_movie_path(movie)
          %h3= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' }

app/views/movies/new.html.haml
.page-header
  = link_to movies_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New movie
= render 'form'

app/views/movies/show.html.haml
.page-header
  = link_to movies_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_movie_path(@movie), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show movie
%dl.dl-horizontal

app/views/welcome/index.html.haml
.row
  - @movies.each do |movie|
    = link_to movie do
      .col-xs-6.col-sm-6.col-md-4.col-lg-4
        .foto
          = image_tag movie.poster.url(:thumb) if movie.poster.url
        .caption
          %h3= movie.movie_name